### ISSUE TITLE
Enhancement: More keys 

### ISSUE THREAD

**Issue by borjita2019** [superpowers04/FunkinBattleRoyale-Mod#5]
## What is your suggestion, and why should it be implemented?
9 keys, 7 key and 6 key, i want this because i actually want to play 6 key, 9 key and 7 key with friends

**Comment by superpowers04** [comment]
I have no plans on adding multiple keys myself as I have no ideas on how to implement them and cannot play multikey myself due to bad skill level, they could be added using scripts locally though. Maybe I'll add the ability for servers to provide scripts or something

**Comment by superpowers04** [comment]
Closed due to inactivity
